/**
 * Rebuilds the DoodleAI blog index and RSS feed from the post files.
 *
 * The blog is hand-written static HTML — one file per post, no framework.
 * This scans blog/*.html, reads each post's <title>, description and date,
 * then rewrites two things:
 *
 *   blog/index.html  — the card list between the POSTS:START/END markers
 *   rss.xml          — the feed
 *
 * So publishing a post is: drop a new .html file in blog/ with a <title>,
 * a description meta and a date meta. Add an order meta to break ties between
 * posts sharing a date (lower shows first). Everything else updates on deploy.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import path from "node:path";

const LINK = "https://doodleai.app";
const BLOG = "blog";

const esc = (s) =>
  String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const meta = (html, name) =>
  html.match(new RegExp(`<meta\\s+name=["']${name}["']\\s+content=["']([^"']*)["']`, "i"))?.[1] ?? "";

const posts = readdirSync(BLOG)
  .filter((f) => f.endsWith(".html") && f !== "index.html")
  .map((file) => {
    const html = readFileSync(path.join(BLOG, file), "utf8");
    const rawTitle = html.match(/<title>([\s\S]*?)<\/title>/i)?.[1] ?? file;
    return {
      file,
      // Strip any " — DoodleAI" style suffix so cards read cleanly.
      title: rawTitle.split(/\s+[—|]\s+/)[0].trim(),
      description: meta(html, "description").trim(),
      date: meta(html, "date").trim() || "1970-01-01",
      // Optional tie-breaker for posts published the same day; lower shows first.
      order: Number(meta(html, "order")) || 99,
    };
  })
  .sort((a, b) =>
    a.date === b.date ? a.order - b.order || a.file.localeCompare(b.file) : b.date.localeCompare(a.date),
  );

if (!posts.length) {
  console.error("No posts found in blog/ — refusing to write an empty index.");
  process.exit(1);
}

// ---- per-post schema and social tags ---------------------------------
// Posts are hand-written, and hand-written means the boring tags get
// forgotten: none of them had article schema or a social image, so every
// share was a bare link and search engines had no idea these were articles.
// Generated here so a new post gets them by existing, not by remembering.
const BLOCK_START = "<!-- SEO:START — generated by scripts/build-blog.mjs, do not edit by hand -->";
const BLOCK_END = "<!-- SEO:END -->";

for (const p of posts) {
  const file = path.join(BLOG, p.file);
  let html = readFileSync(file, "utf8");
  const url = `${LINK}/${BLOG}/${p.file}`;

  const block = [
    BLOCK_START,
    `  <meta property="og:type" content="article" />`,
    `  <meta property="og:site_name" content="DoodleAI" />`,
    `  <meta property="og:image" content="${LINK}/logo-full.png" />`,
    `  <meta name="twitter:card" content="summary_large_image" />`,
    `  <meta name="twitter:title" content="${esc(p.title)}" />`,
    `  <meta name="twitter:description" content="${esc(p.description)}" />`,
    `  <meta name="twitter:image" content="${LINK}/logo-full.png" />`,
    `  <script type="application/ld+json">${JSON.stringify({
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      headline: p.title,
      description: p.description,
      datePublished: p.date,
      url,
      image: `${LINK}/logo-full.png`,
      author: { "@type": "Person", name: "Michael Gardner" },
      publisher: {
        "@type": "Organization",
        name: "The Insanely Wicked",
        url: "https://theinsanelywicked.com/",
      },
      mainEntityOfPage: { "@type": "WebPage", "@id": url },
    })}</script>`,
    BLOCK_END,
  ].join("\n");

  const from = html.indexOf(BLOCK_START);
  if (from !== -1) {
    const to = html.indexOf(BLOCK_END, from);
    html = html.slice(0, from) + block + html.slice(to + BLOCK_END.length);
  } else {
    // First run: sit the block just before the icon link, which every post has.
    const anchor = '  <link rel="icon"';
    if (!html.includes(anchor)) {
      console.error(`${p.file}: no <link rel="icon"> to anchor the SEO block to`);
      process.exit(1);
    }
    html = html.replace(anchor, block + "\n" + anchor);
  }
  writeFileSync(file, html);
}

// ---- blog/index.html -------------------------------------------------
const indexPath = path.join(BLOG, "index.html");
let index = readFileSync(indexPath, "utf8");
const START = "<!-- POSTS:START — generated by scripts/build-blog.mjs, do not edit by hand -->";
const END = "<!-- POSTS:END -->";
const a = index.indexOf(START);
const b = index.indexOf(END);
if (a === -1 || b === -1) {
  console.error("POSTS:START / POSTS:END markers missing from blog/index.html");
  process.exit(1);
}
const cards = posts
  .map(
    (p) =>
      `    <a class="card" href="/${BLOG}/${p.file}"><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p><span>Read it →</span></a>\n`,
  )
  .join("");
index = index.slice(0, a + START.length) + "\n" + cards + "    " + index.slice(b);

// The index gets a Blog entity listing its own posts, generated for the same
// reason the cards are: so it describes what is actually there today.
const INDEX_SEO_START = "<!-- SEO:START — generated by scripts/build-blog.mjs, do not edit by hand -->";
const indexBlock = [
  INDEX_SEO_START,
  `  <script type="application/ld+json">${JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Blog",
    name: "The DoodleAI Blog",
    url: `${LINK}/${BLOG}/`,
    description:
      "Practical guides to making whiteboard and explainer videos without a design tool.",
    publisher: { "@type": "Organization", name: "The Insanely Wicked", url: "https://theinsanelywicked.com/" },
    blogPost: posts.map((p) => ({
      "@type": "BlogPosting",
      headline: p.title,
      description: p.description,
      datePublished: p.date,
      url: `${LINK}/${BLOG}/${p.file}`,
    })),
  })}</script>`,
  BLOCK_END,
].join("\n");

const ia = index.indexOf(INDEX_SEO_START);
if (ia !== -1) {
  const ib = index.indexOf(BLOCK_END, ia);
  index = index.slice(0, ia) + indexBlock + index.slice(ib + BLOCK_END.length);
} else {
  index = index.replace('  <link rel="icon"', indexBlock + "\n" + '  <link rel="icon"');
}
writeFileSync(indexPath, index);

// ---- rss.xml ---------------------------------------------------------
const items = posts
  .map((p) => {
    const url = `${LINK}/${BLOG}/${p.file}`;
    return `    <item>
      <title>${esc(p.title)}</title>
      <link>${esc(url)}</link>
      <guid isPermaLink="true">${esc(url)}</guid>
      <pubDate>${new Date(`${p.date}T09:00:00Z`).toUTCString()}</pubDate>
      <description>${esc(p.description)}</description>
    </item>`;
  })
  .join("\n");

writeFileSync(
  "rss.xml",
  `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>DoodleAI Blog</title>
    <link>${LINK}/${BLOG}/</link>
    <description>Practical guides to making whiteboard and explainer videos without a design tool.</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <atom:link href="${LINK}/rss.xml" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>
`,
);

console.log(`blog rebuilt — ${posts.length} posts (index, rss, per-post schema), newest ${posts[0].date}`);
