/**
 * Rebuilds the DoodleAI blog index and RSS feed from the post files.
 *
 * The blog is hand-written static HTML — one file per post, no framework.
 * This scans blog/*.html, reads each post's <title>, description and date,
 * then rewrites two things:
 *
 *   blog/index.html  — the card list between the POSTS:START/END markers
 *   rss.xml          — the feed
 *
 * So publishing a post is: drop a new .html file in blog/ with a <title>,
 * a description meta and a date meta. Add an order meta to break ties between
 * posts sharing a date (lower shows first). Everything else updates on deploy.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import path from "node:path";

const LINK = "https://doodleai.app";
const BLOG = "blog";

const esc = (s) =>
  String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const meta = (html, name) =>
  html.match(new RegExp(`<meta\\s+name=["']${name}["']\\s+content=["']([^"']*)["']`, "i"))?.[1] ?? "";

const posts = readdirSync(BLOG)
  .filter((f) => f.endsWith(".html") && f !== "index.html")
  .map((file) => {
    const html = readFileSync(path.join(BLOG, file), "utf8");
    const rawTitle = html.match(/<title>([\s\S]*?)<\/title>/i)?.[1] ?? file;
    return {
      file,
      // Strip any " — DoodleAI" style suffix so cards read cleanly.
      title: rawTitle.split(/\s+[—|]\s+/)[0].trim(),
      description: meta(html, "description").trim(),
      date: meta(html, "date").trim() || "1970-01-01",
      // Optional tie-breaker for posts published the same day; lower shows first.
      order: Number(meta(html, "order")) || 99,
    };
  })
  .sort((a, b) =>
    a.date === b.date ? a.order - b.order || a.file.localeCompare(b.file) : b.date.localeCompare(a.date),
  );

if (!posts.length) {
  console.error("No posts found in blog/ — refusing to write an empty index.");
  process.exit(1);
}

// ---- blog/index.html -------------------------------------------------
const indexPath = path.join(BLOG, "index.html");
let index = readFileSync(indexPath, "utf8");
const START = "<!-- POSTS:START — generated by scripts/build-blog.mjs, do not edit by hand -->";
const END = "<!-- POSTS:END -->";
const a = index.indexOf(START);
const b = index.indexOf(END);
if (a === -1 || b === -1) {
  console.error("POSTS:START / POSTS:END markers missing from blog/index.html");
  process.exit(1);
}
const cards = posts
  .map(
    (p) =>
      `    <a class="card" href="/${BLOG}/${p.file}"><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p><span>Read it →</span></a>\n`,
  )
  .join("");
index = index.slice(0, a + START.length) + "\n" + cards + "    " + index.slice(b);
writeFileSync(indexPath, index);

// ---- rss.xml ---------------------------------------------------------
const items = posts
  .map((p) => {
    const url = `${LINK}/${BLOG}/${p.file}`;
    return `    <item>
      <title>${esc(p.title)}</title>
      <link>${esc(url)}</link>
      <guid isPermaLink="true">${esc(url)}</guid>
      <pubDate>${new Date(`${p.date}T09:00:00Z`).toUTCString()}</pubDate>
      <description>${esc(p.description)}</description>
    </item>`;
  })
  .join("\n");

writeFileSync(
  "rss.xml",
  `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>DoodleAI Blog</title>
    <link>${LINK}/${BLOG}/</link>
    <description>Practical guides to making whiteboard and explainer videos without a design tool.</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <atom:link href="${LINK}/rss.xml" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>
`,
);

console.log(`blog index + rss.xml rebuilt — ${posts.length} posts, newest ${posts[0].date}`);
