// ---------------------------------------------------------------------------
// Wicked Stacks blog. One place to edit every post.
//
// Body lines starting with "## " render as subheadings; everything else is a
// paragraph. Each post points at one product (its CTA box) via productSlug.
// ---------------------------------------------------------------------------

export interface Post {
  slug: string;
  title: string;
  date: string; // ISO, used for sorting + display
  category: string;
  excerpt: string;
  body: string[];
  productSlug: string; // CTA at the end of the post
  videoUrl?: string; // optional YouTube link featured in the post
}

export const POSTS: Post[] = [
  {
    slug: "cant-willpower-your-way-out",
    title: "You Can't Willpower Your Way Out of a Design Problem",
    date: "2026-08-27",
    category: "Mind & Life",
    excerpt:
      "Most phone advice is a scolding with a step count attached. It fails for the same reason every time \u2014 it treats a lost fight as a character flaw.",
    body: [
      "Almost every piece of advice about your phone is a scolding with a step count attached. Try harder. Want it more. Be the sort of person who simply does not pick it up.",
      "It has never worked for anybody, and the reason is not mysterious. You are not in a fair fight. Treating a lost fight as a character flaw just adds shame on top of the exhaustion, and shame has never once made anybody better at concentrating.",
      "## Work out the bill before you try to fix anything",
      "The usual mistake is jumping straight to solutions. New app, new rule, new system, quietly abandoned by Thursday.",
      "Do the accounting first, and do it properly \u2014 not a vague sense that you are on your phone too much. Itemised. What did this actually cost you in the last seven days?",
      "Hours is the obvious line and the least interesting one. The expensive items are the ones you never invoice yourself for. The conversation you were physically present at and can remember nothing about. The book you have restarted four times. That specific flavour of tiredness that comes from a day where you were busy without interruption and produced nothing you could point at.",
      "There are two reasons to do this before anything else. You cannot get properly motivated about a problem you have only felt vaguely. And without a starting number, you will never know whether the thing you changed afterwards actually did anything.",
      "## Notifications are not neutral",
      "A notification is not information. It is a request, sent by somebody with a commercial interest, at a moment they chose rather than one you did.",
      "The default settings on a new phone are not a neutral baseline that somebody arrived at by careful thought about your wellbeing. They are the settings that produced the best numbers in testing. Every single one of them is a decision made in a room you were not in.",
      "Which means turning them off is not an act of discipline. It is just correcting somebody else's default.",
      "## Boundaries have to survive other people",
      "This is where most attempts fall apart. It is easy to decide you will not check work messages after six. It is much harder when your boss messages at 4:53pm on a Friday and you can see the three dots.",
      "A boundary that only works when nobody tests it is not a boundary, it is a preference. The useful version is decided in advance, in specific terms, and it accounts for the fact that other people will push on it \u2014 not because they are villains, but because they have their own Friday going on.",
      "## Focus is a muscle you have not used in a while",
      "If you cannot read for forty minutes any more, that is not evidence that something is permanently broken in you. It is evidence of detraining, which is a very ordinary thing that happens to any capacity you stop using.",
      "Nobody who had not run in six years would take one painful mile as proof that they are constitutionally incapable of running. They would take it as the starting point. The same logic applies here and almost nobody extends it to themselves.",
      "## Design the room, not just the rules",
      "Willpower is a terrible tool and an even worse plan. Distance is a far better one.",
      "If the phone is on the desk face down, you are relying on your own restraint every few minutes for eight hours. If it is in another room, you are relying on it once. Every rule you can replace with an arrangement of furniture is a rule you no longer have to enforce.",
      "## The part nobody mentions",
      "Here is the uncomfortable bit, and it is the reason most of the practical advice fails even when people follow it.",
      "A lot of reaching for the phone has nothing to do with the phone. It happens in the gap \u2014 the moment things go quiet and the internal commentary starts up. The half-formed worry, the thing you said in 2019, the list of what you should have done by now.",
      "The scroll is not entertainment at that point. It is a way of not being alone in a room with that voice.",
      "Which means anybody who successfully removes the distraction and has not dealt with what the distraction was covering will find the quiet unbearable and go straight back. That is not weakness. It is a completely reasonable response to sitting still with something unpleasant and having nothing to do about it.",
      "You have to handle that part too, or the rest is just rearranging the furniture around a problem you have decided not to look at.",
      "## Do this one thing this week",
      "Do not change anything yet. Just write the bill.",
      "One week, one note on paper. Every time you notice you have surfaced from your phone without deciding to go in, write down what you were supposed to be doing instead. Do not judge it, do not fix it, just record it.",
      "At the end of the week you will have something better than a resolution. You will have evidence \u2014 and, most usefully, a pattern showing you the specific times of day it happens, which is where any change is actually going to have to go.",
      "The Overwhelm Detox is eleven chapters on all of this \u2014 the accounting, the notifications, the boundaries, rebuilding focus, designing your environment, and the inner critic that gets loud the second things go quiet. Nobody is asked to delete their accounts, move to a cabin, or feel guilty about liking the internet. It comes with three audio deep-dives and four short videos built from the same material.",
    ],
    productSlug: "the-overwhelm-detox",
    videoUrl: "https://youtu.be/MIBZRMtKWWM",
  },
  {
    slug: "digital-doppelgangers",
    title: "Digital Doppelg\u00e4ngers: Why Algorithms Value Your Avatar More Than Your Life",
    date: "2026-08-27",
    category: "Mind & Life",
    excerpt:
      "There is a second version of you assembled out of your scroll speed, your hesitations and the thing you nearly bought. It gets treated better than you do, and it will outlive you.",
    body: [
      "There are two of you. There is the one reading this, and there is the one assembled out of your scroll speed, your hesitations, the thing you searched at two in the morning and the thing you nearly bought and did not.",
      "Only one of those two is commercially interesting, and it is not you.",
      "## The double you build on purpose",
      "Some of it is deliberate. The photograph you picked, the job title you use, the opinions you are willing to have in public. Everybody does this and it is not dishonesty \u2014 you have always spoken differently to your boss than to your oldest friends. Online it simply happens in front of all of them at once, so the performance gets more careful.",
      "But the deliberate half is the small half, and it is not the half anybody is buying.",
      "## The double that gets built for you",
      "The valuable version is assembled without your involvement, out of things you would never think to say about yourself.",
      "Not your age and your postcode. Those are cheap and everyone has them. What is worth money is the shape of your worry. How fast you scroll. Where you slowed down. Which clip you watched twice. The half second of hesitation before you carried on.",
      "From enough of that, a system can work out that you are a new parent who feels guilty about what you are feeding your child. Nobody told it. You never typed it anywhere. It can then walk you, in about ninety seconds, from an idle scroll to an alarming article about what is in ordinary food, straight into an advert for a wildly overpriced organic blanket.",
      "That sequence is not a coincidence and it is not an insult aimed at you personally. It is the product working exactly as designed.",
      "## Your double gets judged in rooms you will never see",
      "This is where it stops being about advertising.",
      "Hand a machine-learning system a pile of mortgage applications and instruct it to ignore race, and it will. It will then look at postcodes, browsing habits, spending patterns and where somebody shops \u2014 and those things carry the history anyway, because the history is what shaped them.",
      "So decades of human bias get automated, scaled up and given a clean mathematical finish. Nobody in the building has to hold a single prejudice for the output to reproduce one. And because the model is a black box even to the people running it, there is frequently nobody who can explain to the person who was refused why they were refused.",
      "Rules do exist. Europe has its data regulation, California has its own. They are aimed at an industry of data brokers built specifically to be hard to see into, which makes it an uphill fight \u2014 and it is being fought on behalf of your double rather than you.",
      "## Invented doubles now outperform real people",
      "The creator economy started with accidental celebrities in messy bedrooms explaining knitting patterns and reviewing video games badly. People trusted them precisely because there was obviously nothing behind it \u2014 no budget, no crew, no angle.",
      "It is now a corporate hierarchy. Brands spend serious money on small local accounts for one reason: those accounts still have the asset that famous people have spent, which is looking like a person instead of a billboard.",
      "Meanwhile, entirely computer-generated influencers have built substantial followings, signed deals with fashion labels and released music, while never having existed at all. The audience knows. It works anyway.",
      "That is the whole argument compressed into a single fact. People say they want authenticity. What they actually respond to is a convincing performance of it \u2014 and a performance can be manufactured.",
      "## What happens when the performance slips",
      "The tell is what the public does the moment it catches a fake.",
      "Fyre Festival sold a luxury island event through coordinated posts of plain orange squares. What turned up was disaster-relief tents and a cheese sandwich in a styrofoam box, and the sandwich became considerably more famous than the festival.",
      "Pepsi ran an advert in which a supermodel defused a protest by handing a police officer a can. It was pulled almost immediately, because the borrowing was too obvious to survive contact with anybody.",
      "Then the reverse. KFC's UK operation ran out of chicken \u2014 a genuinely absurd failure for a chicken restaurant. They bought a full-page newspaper advert showing an empty bucket with the letters rearranged to spell FCK, and apologised without a single excuse in it. The anger stopped more or less on the spot.",
      "The difference was not budget or cleverness. One of them told the truth about itself at its own expense. The double dropped for a moment and there was a person behind it.",
      "And when it is real from the start, the same network does enormous good \u2014 strangers' medical bills covered by people who will never meet them, causes carried past the gatekeepers who used to decide what counted as news.",
      "## The double outlives you",
      "One more thing worth sitting with, because it is coming rather than hypothetical.",
      "You are producing, every day, an enormous archive. Messages, voice notes, searches, photographs, the specific way you phrase things when you are tired. It is more than enough material to build something that sounds like you.",
      "There is nothing technical preventing a company from assembling that after you die and selling access to your family. A synthetic version that answers in your voice, using your turns of phrase, indefinitely.",
      "Whether that is a comfort or a horror is a real question, and it will not be settled by the people who lost you. It will be settled by whoever holds the archive, and by whatever the terms of service happened to say.",
      "## Do this one thing this week",
      "You cannot delete the double. You can starve it a little, and it is ordinary practical work rather than a retreat into the woods \u2014 most people cannot leave, because the work is in there.",
      "Three things. Turn off every notification that is not a human being contacting you directly. Decide the hours the non-essential apps are allowed and hold to it. And put the phone in a different room when you sleep \u2014 not face down, not on silent, a different room.",
      "None of that is a moral position. It is just declining to hand over the material for free.",
      "The Digital Tapestry follows the rest of this thread \u2014 where the machinery came from, what it does to people, and how the creator economy actually works underneath the branding. Full audiobook included.",
    ],
    productSlug: "the-digital-tapestry",
  },
  {
    slug: "the-algorithm-is-not-a-librarian",
    title: "The Algorithm Is Not a Librarian. It's a Party Host.",
    date: "2026-08-27",
    category: "Mind & Life",
    excerpt:
      "A librarian shelves the books and leaves you alone. This host reads your face, crosses the room, and surrounds you with ten furious strangers \u2014 because agitated guests stay later.",
    body: [
      "You think you walked into a park to have a quiet conversation with your friends. In fact the grass is counting your steps, the benches are working out how you feel about what you just said, and the paths quietly rearrange themselves depending on which way the park has decided it can get you to walk.",
      "That is not a metaphor about the future. It is a fairly plain description of opening an app.",
      "## We used to build the rooms ourselves",
      "The early internet was slow and clumsy and it looked terrible, and it had one property we have not managed to get back: you went to it on purpose.",
      "Bulletin boards, newsgroups, forums you had to go and find. Nobody was recommended anything. You turned up because you cared about the topic, and everything about you that normally gets judged first \u2014 your face, your clothes, where you live, how you sound \u2014 was invisible. You were whatever you typed. People found each other over genuinely obscure shared obsessions, and everything appeared in the order it was posted.",
      "Then came the era where an ordinary person wrote their own HTML, badly, and built something recognisably theirs. Hideous backgrounds, a song that started playing without permission, a list of friends they had actually chosen.",
      "That period did not die of natural causes. Fast connections, a phone in every pocket and machine learning all arrived at once, and the job of ordering the internet was handed from human beings to a system with a commercial target.",
      "## What is actually being sold",
      "Here is the part worth sitting with: your connection to other people is not the product. It is the bait.",
      "The product is your behaviour \u2014 and not just the obvious parts. How long you hovered. Where you stopped scrolling and came back. What you started typing and deleted. All of that gets assembled into a working model of what you are likely to do next, and the model is the thing with the price on it.",
      "## Not a librarian. A party host.",
      "The usual defence of algorithmic sorting is that it is a librarian. Billions of books dumped on the floor, somebody has to shelve them.",
      "It is not a librarian. It is a party host, and a manipulative one.",
      "You are at a gathering. Somebody mentions a subject that visibly bothers you. A decent host changes the subject. This host reads your face, crosses the room immediately, and surrounds you with ten furious strangers shouting about that exact thing.",
      "Not to inform you. Not to find you your people. It does it because the numbers say agitated guests stay later.",
      "Nothing in the system is aiming at whether something is true, or useful, or fair. It aims at one figure, which is how long the device stays in your hand. Careful and qualified and boring-but-correct does not move that figure. Anger moves it instantly. So anger is what the room is built to hand you.",
      "## Everyone you know is now one audience",
      "In ordinary life you are several slightly different people, and that is not dishonesty. It is basic social competence. You talk one way to your boss, another to your wife, another to your grandmother, another to the friends you have had since you were fifteen. There is a front room and a back room, and knowing which one you are standing in is most of getting along with anybody.",
      "Post something online and every one of those rooms merges into one. Your employer, your relatives, someone who dislikes you and eight thousand strangers are now a single audience, at the same moment, with no walls between them.",
      "There is only one way to survive that, and everyone arrives at it eventually: you flatten yourself. You broadcast the version of you that could not possibly cause a problem for any of those people. Sanded down, checked over, safe.",
      "Which is what makes \u201cjust be authentic\u201d such an odd piece of advice. The reward is not for being authentic. It is for performing authenticity convincingly. Creators work this out quickly \u2014 that staying visible means supplying the machine with a steady run of personal difficulty and personal joy, released at the right size at the right moment. The people watching form a real attachment, in one direction only, to something that is by then a carefully maintained product.",
      "Everybody else, meanwhile, is measuring an unedited Tuesday afternoon against a scroll of other people's best moments. That was never a fair comparison and it was never meant to be one.",
      "## The next version is worse, and it is close",
      "There is a lot of noise about the next internet fixing all this \u2014 new protocols, ownership, decentralisation. Turning every social interaction into a small financial transaction does not dismantle who holds the power. It renames them.",
      "The thing actually worth watching is the hardware. Headsets and glasses do not function without sensors pointed back at you, and those sensors measure where your eyes go, how wide your pupils open, what your face does in the quarter second before you have decided how you feel, how fast your heart is beating.",
      "Every one of those was private until now, and none of it can be guessed from a click. A system with that information does not have to infer your mood. It can watch it happen and change what is in front of your eyes while it does.",
      "That is a change in kind, not degree. Today the room reacts to what you did. Next, it reacts to what your body is doing before you have decided anything at all.",
      "## None of this means log off",
      "Real connection still happens in these places. People find their people, get help at three in the morning, build things together that could not have existed otherwise.",
      "But it happens in spite of how the room is built, not because of it. Confusing those two is how people end up blaming their own weak willpower for what is actually a design decision made in a meeting they were not invited to.",
      "## Do this one thing this week",
      "Every time you pick up your phone and open a feed, stop for five seconds and ask two questions. Who built this room? And what is it trying to get out of me right now \u2014 attention, anger, envy, a purchase?",
      "You will not always land on an answer. Asking anyway is the whole difference between being a guest and being the raw material.",
      "This is one thread out of The Digital Tapestry, which pulls the rest of it apart \u2014 the history, the psychology, the creator economy and the misinformation machinery \u2014 without the lecture. The full audiobook comes with it.",
    ],
    productSlug: "the-digital-tapestry",
  },
  {
    slug: "self-righteousness-is-not-confidence",
    title: "Self-Righteousness Is Not Confidence. It's Fear.",
    date: "2026-08-27",
    category: "Mind & Life",
    excerpt:
      "The person who cannot let a disagreement go is not the most certain one in the room. They are the one who cannot afford to be wrong about anything.",
    body: [
      "There is a particular kind of person who cannot let a disagreement go. Not the one who argues well \u2014 the one who cannot stop. Who needs you to concede. Who is still going long after the point stopped mattering to anybody at the table.",
      "It looks like conviction. It is almost always the opposite.",
      "Genuine confidence is quiet and unusually flexible. It can pick up a piece of contradictory evidence, turn it over, and put it back down without anything collapsing. It can say I had not considered that. Nothing about that sentence costs it anything.",
      "Self-righteousness cannot do any of that, because for the self-righteous person the disagreement was never about the topic.",
      "## What is actually at stake",
      "Underneath the certainty sits a very simple and very uncomfortable set of questions. If I am wrong about this, what else am I wrong about? Is the whole structure I built my sense of being a decent person on flawed? Do the people who agree with me stop agreeing with me?",
      "Nobody wants to open that door in the middle of an argument at a dinner table. So the door stays shut and the volume goes up. The certainty is not strength holding a position. It is the effort of holding the door.",
      "Which is exactly why calling someone a hypocrite never works. You are not asking them to reconsider a fact. You are asking them to open the door \u2014 and they will not do that while you are standing there watching.",
      "## Your brain retains counsel",
      "Challenge a belief somebody actually cares about and something old and unhelpful takes over. The body handles the idea roughly the way it handles a physical threat: pulse up, jaw tight, the careful reasoning shoved somewhere at the back. Whatever you say next arrives in a room where nobody is listening.",
      "What has taken over is not analysis. It is advocacy. The mind stops working like a judge weighing evidence and starts working like a defence attorney with a client it has already decided to acquit \u2014 building the case backwards from the verdict, admitting whatever helps and quietly losing the rest.",
      "You can watch it run on people you know. If you have decided a coworker is rotten, them leaving the coffee pot empty gets filed as proof. Them staying late to help you finish something gets dismissed as angling for overtime. Nothing they do can count in their favour, because the file was closed before any of the evidence came in.",
      "It scales up without effort. A cashier is short with you and throws your receipt, and you conclude something about who they are. You are short with somebody after six hours on your feet under a broken scanner and a manager who has been shouting since noon, and you conclude something about the day you were having. Same behaviour, two completely different explanations, and the generous one is always the one you happen to be standing inside.",
      "## This is not a politics problem",
      "The easy version of this argument stops at politics, because politics is where it is loudest and where it is comfortably somebody else's fault. It does not stop there.",
      "Vegans and meat-eaters do it to each other with total sincerity \u2014 bloodthirsty on one side, fragile on the other. People with taste in music do it to people who like what is popular. Older people file the young as lazy and screen-addicted, and younger people file their elders as dinosaurs who had it easy. Every one of those is the same move: a label cheap enough to apply in under a second, stuck to a person complicated enough to take ten years to understand.",
      "It saves an enormous amount of mental effort, and that is the entire appeal. Working out what somebody actually thinks and why is slow, and it carries the real risk of discovering they had a reason.",
      "## Three things that are harder than they sound",
      "The alternative is not agreeing with everybody, and it is not pretending everything is equally true. It is three specific habits, none of which feel remotely virtuous while you are doing them.",
      "**Humility.** Accepting that you are one person looking through a keyhole. Not that you are wrong \u2014 that your view is partial, on most subjects, permanently.",
      "**Tolerance.** Putting up with something you genuinely dislike without trying to get the person holding it silenced, removed, or made an example of. This is the unglamorous one. It is also the one doing the work.",
      "**Patience.** Choosing curiosity over condemnation in the sixty seconds where condemnation would feel fantastic.",
      "None of this cancels accountability. Admitting your own shit stinks does not mean nothing stinks, and it does not mean everything stinks equally. It removes one specific thing: the quiet assumption that you are the exception, and that whatever you were about to do to somebody is therefore fine.",
      "## Do this one thing this week",
      "Next time somebody says something that makes your chest go tight, do not respond. Wait sixty seconds. Then ask them one genuine question about why they believe it \u2014 a real question, not an argument wearing a question mark.",
      "You learn something either way. Either they have a reason you had not considered, or they do not have one at all and find that out themselves, out loud. Both of those beat the fight you were about to have.",
      "This is one conversation out of a growing audio collection about hypocrisy, bias, and the mess everyone is standing in \u2014 including the person making the argument. If this is the kind of thinking you want more of, the whole collection is here.",
    ],
    productSlug: "your-shit-stinks-too",
  },
  {
    slug: "your-blisters-are-real-so-is-your-tailwind",
    title: "Your Blisters Are Real. So Is Your Tailwind.",
    date: "2026-08-27",
    category: "Mind & Life",
    excerpt:
      "The people most convinced they are immune to bias are reliably the ones making the worst mistakes — and telling them so guarantees they stop listening.",
    body: [
      "The people who consider themselves the most educated, the most open-minded and the most morally switched-on are frequently the ones making the worst mistakes, while remaining entirely convinced they are immune.",
      "We want morality to work like structural engineering. When a bridge fails, an inspector finds the microfracture in the steel, names the point of failure, replaces the part, and everyone goes home. Clean, binary, comforting.",
      "Human bigotry does not work like that. There is no single beam to point at. So instead of sitting with the mess, we build small moral thrones, point at the obvious villains, and decline to look at the inconsistencies in our own behaviour.",
      "## We love equality until it asks for something",
      "Almost everyone will tell you they value equality. It is the socially correct answer and it costs nothing to give.",
      "Move from the principle to anything concrete — actual policy, actual resources directed at actual groups — and the agreement thins out considerably. What is interesting is not that the drop happens. It is that nobody believes they are part of it.",
      "The mechanism is simple and it runs in all of us. When someone cuts you off in traffic, you explain it with the person: they did it because they are selfish. When you cut someone off, you explain it with the situation: sun in your eyes, late for something, no harm meant.",
      "We give ourselves endless credit for our intentions while judging everyone else purely on their impact. And being told this directly does not help. Tell someone they are being a hypocrite and they do not reconsider — they defend. The critique lands as an attack, and nobody thinks clearly while under attack.",
      "## Which is why you start lower down",
      "Before you can talk about anything structural, the ego has to be asleep. That is what the crude version is for: your shit stinks too.",
      "Reminding people of their basic, universal, animal messiness takes away the option of playing the wronged party. It is not absolution. It is a punch in the gut that makes the next sentence audible.",
      "There is a real risk in this move and it is worth naming. If universal fallibility becomes the whole story — if redlining and wage gaps get filed alongside spilling water on the kitchen floor — then you have handed comfortable people a very convenient exit.",
      "Privilege is not a personal slip. It is the floor being tilted.",
      "Peggy McIntosh described it as an invisible package of unearned assets. It runs from the trivial — plasters that match your skin, seeing people like you portrayed well on television — to the structural: loan approvals, and walking down a street without being regarded as a question that needs answering.",
      "Tell a runner they have been going downhill with the wind behind them while others carry rocks uphill, and their first response is to talk about their blisters. The blisters are real. They trained hard, it hurt, none of that is invented. The tailwind is also real. Both things are true at once, and the entire difficulty is getting anyone to hold both at the same time.",
      "Call them a villain and the defensiveness wins. Establish that everyone in the conversation is a flawed animal, including you, and they might actually look at the track.",
      "## The machine is built to stop this working",
      "Modern platforms do not help us examine our blind spots. They are engineered to sell them back to us.",
      "The feed is a slot machine. You pull the lever and find out whether you get a small reward or a hit of rage, and the unpredictability is the entire point — it is the same conditioning schedule a casino uses, and it works on us for the same reasons.",
      "Outrage travels furthest, so the machine inflates the person explanation relentlessly. Contradictory, inconsistent, actual human beings get flattened into one-dimensional avatars: pure or bankrupt, nothing in between. One screenshot, stripped of everything around it, is enough to mark someone permanently — and the marking generates clicks, which generate revenue.",
      "Underneath it is ordinary pack instinct. Belonging feels safe. We forgive our own side and credit their wins to brilliance. The other side gets luck for their wins and character for their failures. Eventually we define ourselves less by anything we have built than by who we are against.",
      "## The radical bit is patience",
      "Getting out of the boxes needs an old idea back: different strokes for different folks. Muhammad Ali used it, Sly and the Family Stone sang it, and it long predates both.",
      "It does not mean looking at wage gaps or discriminatory lending and calling them lifestyle preferences. It means extending some patience to the messy, half-formed humans caught in the machinery — including the ones doing it badly.",
      "If someone is stumbling through the awkward, defensive early process of noticing their own advantages, and the response is to brand them a monster, they will go straight back to the room where nobody asks them to notice anything. You have not won. You have removed the only person who was moving.",
      "Progress here is slow and unglamorous. It looks less like a moral crusade and more like a dog skidding across a kitchen floor, getting up, licking the mess, and asking for a treat.",
      "And if the foundation stays untouched — if everyone underneath still believes they personally are the exception — then whatever gets changed from the top will be resented and quietly dismantled the moment attention moves on. You cannot fix the systems without dealing with the flawed creatures running them.",
      "## Do this one thing this week",
      "Catch the exact moment you feel righteous indignation at someone, online or in person. Do not post anything. Do not decide what they are.",
      "Just name the external circumstance you are refusing to consider on their behalf — the one you would reach for instantly if it were you.",
      "You will not enjoy how easy it is to find.",
      "This is one conversation out of a growing audio collection about hypocrisy, bias, and the mess everyone is standing in — including the person making the argument. If this is the kind of thinking you want more of, the whole collection is here.",
    ],
    productSlug: "your-shit-stinks-too",
  },
  {
    slug: "if-your-partner-dies-their-spouse-owns-half-your-company",
    title: "If Your Partner Dies, Their Spouse Owns Half Your Company",
    date: "2026-08-27",
    category: "Business",
    excerpt:
      "Monday morning, your new equal partner is a grieving spouse who wants cash, not your ten-year roadmap — and they have the votes to liquidate everything you built.",
    body: [
      "If your fifty-fifty business partner dies tomorrow, you may wake up on Monday to discover your new equal partner is their grieving spouse.",
      "That person has no interest in your ten-year roadmap or your next product launch. They want cash, quickly. And without the right paperwork in place, they hold exactly the voting authority needed to force a liquidation of your life's work so they can buy a condo in Florida.",
      "Nobody wants to think about this, which is precisely why almost nobody has handled it.",
      "## Compliance is a seat belt",
      "Founders love the marketing side. Growth tactics, positioning, clever pricing. Legal structure feels like a chain that restricts movement, so it gets pushed to next quarter permanently.",
      "But compliance is a seat belt. You do not wear one because you plan to drive into a wall. You wear one because you cannot control the other drivers — the competitor, the disgruntled contractor, the customer who decides to sue.",
      "The bill for skipping it is entirely preventable, and it always arrives at the worst possible moment.",
      "## The corporate veil is not automatic",
      "The foundational rule is a permanent separation between you the person and the company the entity. Operate as a sole proprietor and there is no separation at all — you and the business are legally the same thing.",
      "There is a case in the book about an e-commerce founder doing two million a year in revenue who never got round to filing. A customer sued over an allergic reaction that turned out to be caused by their own pre-existing condition. Being right did not help. Defence costs hit a hundred and fifty thousand, and with no entity in the way, the plaintiff's lawyers went straight at his personal account, his family savings and his house. He settled and lost everything.",
      "Filing the formation documents is not the end of it either. Neglect the entity and a judge will pierce the veil, remove the protection entirely, and expose your personal assets anyway. Three things keep it standing:",
      "**Never mix the money.** Company card for personal groceries, a streaming subscription, a mortgage payment, a pack of gum — every one is a crack. In litigation, opposing counsel subpoenas the bank records specifically hunting for a pattern of personal use, because that pattern lets them argue the company is just you wearing a hat.",
      "**Keep the formalities.** Document decisions, hold the annual meeting even if it is a meeting with yourself, file state reports on time, keep signed minutes. The law grants solo operators no exemption. A company of one still needs a paper trail showing the company thinks separately from the person.",
      "**Capitalise it properly.** Put a hundred dollars into the account and take on half a million in debt and you have proved to a court that the entity was a shell that was never meant to stand on its own.",
      "## Choosing the structure",
      "This is a question of matching how you actually operate to how you want to be taxed.",
      "An **LLC** gives you pass-through taxation. The entity pays no federal income tax; profit flows onto your personal return, and you avoid being taxed twice.",
      "A **C Corporation** is an eighteen-wheeler. Absurd for fetching groceries, necessary if you are hauling venture capital — investors require one because they need clean cap tables and share classes with different voting rights. The cost is double taxation: the company pays corporate tax on profit, then shareholders pay again on dividends.",
      "An **S Corporation** election suits profitable service businesses. Instead of self-employment tax on every dollar of profit, you pay yourself a reasonable salary and take the rest as a distribution, which is not subject to self-employment tax. The saving is real and it compounds annually.",
      "The trap is obvious once stated: pay yourself an artificially tiny salary against a large distribution and you are inviting an audit, reclassification, back taxes and penalties. Reasonable means reasonable.",
      "## The business prenup",
      "Handshakes and goodwill do not survive contact with grief and money. A buy-sell agreement has to be negotiated while everyone still likes each other, and it needs four things.",
      "**Triggering events.** Death, permanent disability, someone wanting out, and divorce. Skip the divorce provision and a family court judge can hand company equity to your partner's ex — putting you in business with someone who has every reason to dislike you.",
      "**A valuation formula.** Agree the maths in advance — a multiple of trailing earnings, or a named third-party appraiser. Anything to remove subjective argument at the exact moment nobody is thinking clearly.",
      "**A way to actually pay for it.** Almost no business has the cash sitting there to buy out a dead partner's heirs. Company-owned term life policies on each partner fund that instantly, without touching working capital. For departures that are not deaths, define an instalment plan paid out of future earnings.",
      "**Right of first refusal.** A departing partner has to offer their shares to the existing owners first, at the agreed valuation, inside a fixed window. Without it, a competitor or an opportunistic buyer can simply purchase their way onto your cap table.",
      "## The assets you cannot see",
      "Failing to secure intellectual property can erase a company overnight, and the two most common failures are quiet ones.",
      "**The name.** A startup spends real money on a logo, prints the cards, buys the domains, builds traction — then receives a cease-and-desist from a business in another state that registered that exact name federally a decade earlier. Thirty days to scrap everything and rebrand. Search the trademark database for phonetic and same-industry conflicts before you fall in love with a name, not after.",
      "**The logo you paid for.** Paying a designer does not mean you own the work. The creator keeps the rights unless the contract contains an explicit work-for-hire clause and a full assignment of intellectual property. Without that specific language you are licensing your own brand from the person who drew it.",
      "One more worth knowing: a patent is a public document. Filing one means publishing the exact schematics for competitors to study and design around. Sometimes a trade secret — compartmentalised knowledge and real non-disclosure agreements — protects you better than a patent ever could.",
      "## Do this one thing this week",
      "Pull up every freelance and contractor agreement your business has ever signed. Search each one for the words work for hire.",
      "If a contract that produced your logo, your site, your app or your copy does not contain that clause and a clear assignment of rights, you do not own the thing you paid for. Fix it now, while the relationship is good and the person will happily sign an assignment, rather than during an acquisition when their lawyer suddenly understands the leverage.",
      "One note, and it is not a formality: this is the shape of the problem, not advice for your specific situation. Company structure and tax elections turn on details — your state, your income, whether you have employees, what you intend to do in three years. The point of a chapter like this is to tell you which questions to take to an attorney and an accountant, so that the hour you pay for is spent well.",
      "This is one idea out of seventeen chapters on building, running, and growing a business — unit economics, market sizing, sales systems, hiring, and the automation math most people never actually run. If the numbers side is where you keep getting caught out, the whole thing is in the book.",
    ],
    productSlug: "complete-business-mastery",
  },
  {
    slug: "bootstrapping-versus-venture-capital",
    title: "You Can Go Bankrupt From Winning",
    date: "2026-08-27",
    category: "Business",
    excerpt:
      "A profitable company signs a Fortune 500 contract and dies three months later. Not from failure — from success it couldn't afford to fund.",
    body: [
      "Here is a way to go out of business that nobody warns you about. You land the biggest contract of your life. A real enterprise client, the kind you have been chasing for two years. You sign it, you deliver, and ninety days later you are insolvent.",
      "Not because the deal was bad. Because the deal was good and you could not afford to fund it.",
      "Large companies pay on net 90. You sign today, you deliver today, and the money lands three months from now. Meanwhile your hosting bill is due on the first, your sales rep wants their commission at the end of the week, and someone has to be paid to onboard the client immediately.",
      "The cash goes out now. The revenue arrives in a quarter. A perfectly profitable business can bleed to death in that gap, and the more successful you are, the wider the gap gets.",
      "## This is the argument for taking the money",
      "It is also the strongest argument anyone makes for venture capital, and I want to give it a fair hearing before I take it apart.",
      "The case goes like this. In a market where a competitor can raise fifty million and you cannot, the money is not a luxury. They hire your senior engineers by offering double. They buy the search inventory for your keywords, which drives your acquisition cost past what your margins can carry. Then they walk into your enterprise prospects and offer the first year free, absorbing a loss on purpose, locking those clients into multi-year contracts you never got to bid on.",
      "None of that requires a better product. It requires a bigger balance sheet.",
      "Hold on to a hundred percent of a company that gets starved out and you own a hundred percent of nothing. That is not a cheap shot. It is arithmetic.",
      "## And here is where the argument stops working",
      "It stops working the moment you notice what the money is actually for.",
      "There is a case in the book — a founder who raised five million for a SaaS platform and gave up forty percent of his company and two board seats to get it. The board wanted three times year-over-year growth. He delivered fifty percent.",
      "Fifty percent growth is a thriving business. In any sane context it is a triumph. But it did not put him on track for the ten-times return the fund's math required, so the board called him a failure, replaced him as CEO, and eventually removed him from the company he built.",
      "He was not failing. He was playing a normal game of business while the people who controlled his board were playing a finance game with different rules and a ten-year clock.",
      "You can argue he did fine — he kept fifteen percent, the company sold for fifty million, he walked away with seven and a half. That is generational money and I am not going to pretend otherwise.",
      "But notice what got traded. Not equity. Authority. He lost the ability to decide what winning meant.",
      "## Constraints are not a consolation prize",
      "When you do not have ten million sitting in a treasury account, you cannot hide anything.",
      "You cannot buy customers at a loss and call it growth. Your acquisition cost has to be lower than your lifetime value from the first month, because if it isn't you cannot make payroll. Every inefficiency shows up immediately as a number you have to fix rather than a line item the runway absorbs.",
      "Capital papers over broken unit economics, and it papers over them for exactly long enough that fixing them stops being possible. Founders see twenty million in the bank and conclude they can scale their losses into profit — the old line about making it up in volume. Then acquisition costs rise, because the warm leads run out and you have to pay to reach the mainstream. Margins compress, because now you need middle management and HR and heavier infrastructure. The overhead explodes and the runway ends at speed.",
      "Bootstrapping forces you to fix that math before you scale, because there is no version where you don't.",
      "## So what do you do about net 90?",
      "Turn the contract down.",
      "I am aware how that sounds. But if the terms would bankrupt you, the deal is not a deal — it is a bet on financing you have not arranged yet.",
      "Go back and ask for thirty percent up front for implementation. Look at invoice factoring, which costs money but does not cost ownership. Restructure the delivery so the expensive part happens after the first payment clears.",
      "All of those are harder than raising a round. That is the point. Every one of them leaves you owning the company at the end.",
      "Using equity to solve a cash conversion problem is trading something permanent for something temporary. You are not building a bridge for yourself. You are building one for a toll collector who wants a very large yield for the privilege of crossing.",
      "## What both sides actually agree on",
      "The honest version of this argument is that the funding question is downstream of a harder one.",
      "Scale before you have validated the model and you are finished either way. A large treasury cannot manufacture demand that isn't there — it only lets you fail louder and considerably more expensively. Capital is an accelerant. If the machine is broken, you are accelerating a broken machine.",
      "And taking money from investors who want a different outcome than you do will destroy the company from the inside no matter how good the unit economics look. A founder who wants a steady profitable business and a fund that needs a ten-times outlier are not disagreeing about tactics. They want different things, and one of them controls the board.",
      "If you take power law money, you have to be willing to play the power law game. The failure is not choosing wrong. It is choosing one and then wanting the other.",
      "## Do this one thing this week",
      "Work out your cash conversion cycle. How many days between paying to deliver something and the money actually landing in your account.",
      "Then ask what happens if your biggest current prospect signs next week on net 90 terms. Can you fund the gap out of what is in the bank right now?",
      "If the answer is no, you do not have a growth problem. You have a financing problem wearing a growth problem's clothes, and it will find you at the worst possible moment — the week you win.",
      "This is one idea out of seventeen chapters on building, running, and growing a business — unit economics, market sizing, sales systems, hiring, and the automation math most people never actually run. If the numbers side is where you keep getting caught out, the whole thing is in the book.",
    ],
    productSlug: "complete-business-mastery",
  },
  {
    slug: "your-crm-is-a-database-of-market-failures",
    title: "Your CRM Is a Database of Market Failures (Start Using It Like One)",
    date: "2026-08-27",
    category: "Business",
    excerpt:
      "Your sales team isn't a mechanism for forcing money out of reluctant prospects. It's a sonar array — and you're throwing away everything it pings back.",
    body: [
      "If you are paying human salaries to grind out every single sale by brute force, the math of your business will eventually break down. You will bleed cash, your customer acquisition cost will stay permanently higher than your lifetime value, and no amount of sales hustle will save you.",
      "Most founders refuse to accept this. When sales stall, the instinct is to double down on trench warfare — grind harder on the phones, wrestle prospects to the ground, offer a desperate discount to soothe the sting of a rejection.",
      "This is stupid.",
      "It comes from treating your product as a static rock and your sales team as unpaid heavy labor whose only job is to push that rock up a hill. You isolate engineering in a basement, let them build whatever strikes their fancy, then punish sales for failing to shove the resulting dead weight onto paying customers.",
      "## Your sales team is a sonar array",
      "A sales team is not a mechanism for forcing money out of reluctant prospects. It is a sonar array.",
      "When your reps make outbound calls, they are pinging the market. The objections that bounce back are not personal insults, and they are not minor hurdles to be smoothed over with clever rhetoric. They are data points showing you exactly where your product is failing to meet reality.",
      "Right now you are probably treating your CRM as a digital Rolodex. Contact names, phone numbers, and worthless notes recording that a prospect \"needs time to think.\"",
      "That is a waste of both the software and the people filling it in.",
      "A properly used CRM is a structured database of market failures. Every time a deal dies, the prospect hands you precise, unvarnished information about why your product is inadequate. Ignore it and tell your reps to call the next lead, and you are choosing to sail blind.",
      "## The seventeen-feature widget",
      "There is a story I tell early in the book about a founder I will call David.",
      "David locked himself in a basement for two years building what he was certain was a revolutionary widget. A masterpiece of over-engineering, seventeen distinct features, including an AI chatbot nobody asked for.",
      "When he finally came out and made a hundred outbound calls, he got a hundred consecutive rejections. He shut the company down and took a job as a product manager.",
      "Most people read that as a warning about over-engineering. Build less, sell sooner. That is not the interesting part.",
      "David did not fail because he was rejected a hundred times. He failed because he took the rejections personally instead of reading his own notes.",
      "Had he actually looked at the data from those brutal calls, a pattern was sitting right there. Nobody cared about sixteen of the features. Nobody wanted the chatbot. But thirty separate prospects had asked about feature number seven — a simple export button.",
      "If David had used his rejections as product inputs, he would not have quit. He would have stripped out sixteen features, killed the chatbot, and relaunched a single-feature widget that a third of his market was actively asking to buy.",
      "Sales grit without product evolution is just self-flagellation. You do not go into the trenches only to close a deal today. You go in to gather the mud that tells you what you should have been building all along.",
      "## Close the loop",
      "To stop bleeding cash on acquisition, sales and product cannot be separate silos. They have to be one loop. Engineering builds a baseline, sales pings the market, and the friction that comes back dictates the next update.",
      "Watch how this plays out on a single objection. Your rep hears the classic brush-off: \"I need to think about it.\"",
      "In a traditional setup, the rep is trained to overcome that verbally, or to throw a discount at it. A good rep digs and finds the real blocker — the prospect cannot buy because your product has no integration with the accounting software they use every day.",
      "In a siloed business, that dies on the call. The rep moves to the next cold outreach and engineering spends the sprint polishing something no customer has ever mentioned.",
      "In an integrated business, that missing integration gets tagged in the CRM. When the tag hits fifty entries, it lands on the engineering team's sprint board as a priority.",
      "That changes what your business actually is. You stop trying to train better salespeople to push a bad product uphill, and start using your salespeople to build a product that needs less selling every quarter.",
      "## Do this one thing this week",
      "Open your CRM and pull every deal lost in the last ninety days.",
      "Throw out the vague rep excuses — bad timing, no budget, went quiet. Group whatever is left strictly by specific missing features or integration gaps.",
      "If a single gap accounts for more than twenty percent of those losses, stop your engineering team from working on whatever vanity update is planned and make that gap the top priority for the next build cycle.",
      "This is one idea out of seventeen chapters on building, running, and growing a business — unit economics, market sizing, sales systems, hiring, and the automation math most people never actually run. If the numbers side is where you keep getting caught out, the whole thing is in the book.",
    ],
    productSlug: "complete-business-mastery",
  },
  {
    slug: "why-motivation-follows-action",
    title: "Why Motivation Follows Action (Not the Other Way Around)",
    date: "2026-08-21",
    category: "Mind & Life",
    excerpt:
      "You're waiting to feel like it. You're going to be waiting forever — because the feeling shows up AFTER you start, not before.",
    body: [
      "Here's the lie almost everybody believes: first you get motivated, then you take action. So you wait. You watch the videos, you make the vision board, you psych yourself up — and maybe you feel a little surge. Then the surge fades, because feelings fade, and you're right back on the couch wondering what's wrong with you.",
      "Nothing is wrong with you. You've just got the machine backwards.",
      "## Action first, feeling second",
      "Motivation is not a prerequisite. It's a result. You don't feel like going for a run and then go — you go, and somewhere around the corner your body says, huh, this isn't terrible, and the next run gets easier to start. You don't wait for inspiration to write; you write a bad paragraph, and the act of writing shakes the next one loose.",
      "Waiting to feel like it is like waiting for perfect weather before starting a journey. Some days the weather never comes. You go anyway, or you don't go at all.",
      "## Make the first step insultingly small",
      "The trick that actually works is shrinking the first action until it's too small to argue with. Not \"work out\" — put on the shoes. Not \"clean the house\" — carry one cup to the sink. Not \"fix my life\" — drink a glass of water and make the bed. Your brain can talk you out of a transformation. It cannot be bothered to talk you out of a glass of water.",
      "Small actions don't feel like they count. They count double. Every one is a vote for the version of you that follows through, and enough votes change the election.",
      "This is one idea out of fourteen chapters on getting unstuck — the shame spirals, the harsh inner voice, the routines that hold when everything else falls apart. If you've been stalled longer than you'd like to admit, the whole map is in the book.",
    ],
    productSlug: "stuck-no-more",
  },
  {
    slug: "four-funding-paths-and-founder-psychology",
    title: "The Four Ways to Fund a Business — and What Each One Does to Your Head",
    date: "2026-08-21",
    category: "Business",
    excerpt:
      "Bootstrapping, borrowing, investors, or customers — where the money comes from changes what you build AND who you become while building it.",
    body: [
      "Ask most people how to fund a business and they'll talk spreadsheets: interest rates, equity percentages, runway. All real. All secondary. The first-order effect of funding isn't financial — it's psychological. Where your money comes from decides who you answer to, what you're afraid of, and what \"success\" is even allowed to mean.",
      "## The four paths, honestly",
      "Bootstrapping keeps you free and keeps you scared — every decision is your money burning. Debt buys speed and sells sleep; the bank doesn't care that you had a slow quarter. Investors hand you fuel and take the steering wheel's margins — you now run a company that must grow, whether or not growing serves you. And funding from customers — actually selling things early — is the slowest-looking path that's secretly the fastest, because every dollar arrives attached to proof that somebody wants what you make.",
      "There's no universally right answer. There is a right answer for your situation, your risk tolerance, and your head. Choosing without knowing yourself is how rational people end up making destructive decisions.",
      "## Hear it argued out loud",
      "I put out a free 12-minute audio deep-dive on exactly this — Four Funding Paths and Founder Psychology — built from the book. Listen on the way to work and you'll know which path fits you by the time you park.",
      "The full book goes a lot further: market sizing three ways, unit economics with the math shown, sales systems, hiring, automation ROI — seventeen chapters, plus the Resource Pack of templates and four bonus audio deep-dives now included.",
    ],
    productSlug: "complete-business-mastery",
    videoUrl: "https://youtu.be/9HCru9FA6VE",
  },
  {
    slug: "how-algorithms-decide-what-you-see",
    title: "How Algorithms Decide What You See (and What That's Costing You)",
    date: "2026-08-21",
    category: "Mind & Life",
    excerpt:
      "Your feed isn't a window into the world. It's a mirror maze built by a machine whose only job is keeping you inside it.",
    body: [
      "Nobody sat you down and asked what you wanted to care about this year. A recommendation system decided, one scroll at a time, by watching what makes you pause, what makes you mad, and what makes you stay. The feed isn't showing you the world — it's showing you whatever keeps you looking at the feed.",
      "## The machine isn't evil. It's obedient.",
      "That's the uncomfortable part. The algorithm isn't out to get you; it's out to serve its actual customer, and its actual customer is the advertiser buying your attention. You're not being persecuted. You're being farmed — politely, efficiently, and with your own enthusiastic participation every time you open the app \"for a second.\"",
      "The costs show up quietly: opinions you absorbed instead of formed, hours that evaporated without memories, a low hum of comparison that makes your real life feel like the off-brand version of everyone else's highlight reel.",
      "## Using it without being used",
      "The answer isn't throwing your phone in a lake. It's understanding the machine well enough that you stop being its raw material — knowing why the feed shows you what it shows you, and choosing on purpose instead of scrolling on autopilot. Attention is the only currency you can't earn back. Spend it like that's true.",
      "The Digital Tapestry digs through all of it — the history, the psychology, the influencer economy, the misinformation machinery — sharp and funny instead of preachy, with the full audiobook included so you can take your brain back on your commute.",
    ],
    productSlug: "the-digital-tapestry",
  },
  {
    slug: "the-50-true-fans-math",
    title: "The 50 True Fans Math: Why You Don't Need to Go Viral",
    date: "2026-08-21",
    category: "Business",
    excerpt:
      "You don't need a million followers. You need fifty people who genuinely want what you make. Here's the arithmetic nobody shows you.",
    body: [
      "Every beginner thinks the goal is going viral. A million views, a flood of customers, the screenshot income. And because that's the goal, most people never start — a million of anything sounds impossible from zero, because it is.",
      "So run the real numbers instead. Say you make something genuinely useful and price it at $20. Fifty true fans — fifty actual humans who trust you — is $1,000. A hundred is $2,000. A product a season and a slowly growing list of people who like your work beats a lottery ticket every single time, because it compounds and lottery tickets don't.",
      "## Where the first fifty come from",
      "Not from ads. Not from hacks. From being findable and being useful: answering real questions where your people already gather, publishing things worth reading, and asking for the sale plainly when you've earned the right. It's slower than the guru promises and faster than staying stuck at zero forever.",
      "## The honest path",
      "From Zero to Online Income is the no-hype version of this whole journey — thirteen chapters from picking an idea you can actually execute to your first sales without an audience, with a workbook that turns each chapter into something you did instead of something you read. No rented Lamborghinis anywhere in it.",
    ],
    productSlug: "from-zero-to-online-income",
  },
  {
    slug: "teaching-kids-money-without-making-it-weird",
    title: "Teaching Kids About Money Without Making It Weird",
    date: "2026-08-21",
    category: "Kids' Corner",
    excerpt:
      "Kids learn money habits by age seven — mostly by watching you. Here's how to make the lessons stick without a single lecture.",
    body: [
      "Researchers say most kids have their core money habits by around age seven. Which is inconvenient, because most parents plan to have \"the money talk\" sometime around never. The good news: kids don't need a lecture. They need a story, a jar, and a grown-up who doesn't panic when they ask what a credit card is.",
      "## Three jars beat one piggy bank",
      "Save, spend, share. When money comes in — birthday, allowance, tooth fairy — it gets split. The split is the lesson: money isn't one thing you hoard or blow, it's a resource you direct. A five-year-old who divides three dollars into jars is doing the same thing a CFO does with a budget, just with stickier hands.",
      "## Let them buy the wrong thing",
      "The five-dollar toy that breaks in an hour teaches more than any speech. Small regrets now are cheap tuition; the same lesson at 25 costs a credit score. Your job isn't preventing every bad purchase — it's making sure the first ones are small and the conversation afterward is kind.",
      "And stories do the heavy lifting best. Penny's Piggy Bank walks little ones through saving, sharing, and smart choices inside a warm, giggly story — with the professionally narrated audiobook included, for car rides and bedtimes when your voice is spent. Read it together; the jars will make sense on their own.",
    ],
    productSlug: "pennys-piggy-bank",
  },
  {
    slug: "nobody-gets-the-high-horse",
    title: "Nobody Gets the High Horse: What My Dog Taught Me About Judgment",
    date: "2026-08-21",
    category: "Mind & Life",
    excerpt:
      "My dog Frankie has never once judged another dog. Humans can't get through breakfast without judging somebody. That gap is the whole story.",
    body: [
      "Frankie — my dog, co-host, and the only member of this household with the moral high ground — has never once judged another dog for how it eats, where it sleeps, or what it rolls in. Humans? We judge strangers in traffic, relatives at dinner, and ourselves in the mirror, all before lunch.",
      "That gap between dog logic and human moralizing is where Your Shit Stinks Too lives. It started as a podcast, me and Frankie, about the one thing people hate admitting: everybody's shit stinks. Including mine. Especially mine. The high horse everyone's trying to ride doesn't actually exist — there's just people standing in the same mess, pointing at each other's shoes.",
      "## Why judgment feels so good (and costs so much)",
      "Judging is cheap superiority. For one free moment, you're the better person — no effort required. But the habit corrodes: it makes honesty with yourself impossible, because the judge can never afford to be a defendant. The people who grow are the ones who can say \"I do that too\" without flinching.",
      "## Start with the free episode",
      "The trailer episode — Frankie's Food Bowl: Dog Logic vs. Human Moralizing — is free on YouTube, four minutes, and it'll tell you whether this series is your kind of uncomfortable. The full collection is about two hours of deep-dives, twelve bucks, price locked forever, and every new episode I make gets added free.",
    ],
    productSlug: "your-shit-stinks-too",
    videoUrl: "https://youtu.be/cyz0DfuaF0k",
  },
  {
    slug: "when-a-kid-says-i-cant-do-it",
    title: "When a Kid Says \"I Can't Do It\"",
    date: "2026-08-24",
    category: "Kids' Corner",
    excerpt:
      "It's almost never about the thing they're looking at. It's about the size of it — and size is the one part you can actually fix.",
    body: [
      "A kid stares at a jigsaw puzzle, a messy bedroom, or a page of homework, and out it comes: I can't do it. Said flatly, like a fact about the world. And the reflex — every parent has it — is to argue. Yes you can. It's easy. You did one just like it last week.",
      "That argument has never worked in the history of children, and there's a reason. You're disagreeing with the wrong sentence.",
      "## They're not describing ability. They're describing size.",
      "What a kid means by \"I can't do it\" is almost never a verdict on their own competence. It's a description of what's in front of them. The thing looks big. It has no edges they can find. There's no obvious place to put a hand.",
      "Adults get this feeling too — we just have politer words for it. We say a project is overwhelming, or that we don't know where to start, or we quietly do something else for three days. Nobody thinks less of us for it. A seven-year-old says the shorter version and gets told they're being difficult.",
      "So arguing about whether they *can* misses it entirely. They're not wrong about being stuck. They're wrong about why.",
      "## The only useful question",
      "Instead of \"yes you can,\" try: what's the very first small piece?",
      "Not the plan. Not the whole approach. One piece, small enough to be boring. For the puzzle: find all the flat edges. For the bedroom: everything that's a book goes on the bed. For the homework: read just the first question out loud, don't answer it yet.",
      "What happens next is the part worth watching. The kid does the boring small thing — and the big thing quietly gets smaller. Not because you gave a speech about perseverance, but because it now has an edge they can hold onto.",
      "Do that four or five times and something better than a tidy bedroom happens: they start doing it without you. You've handed over a move they can make on their own, which is the whole job.",
      "## Don't take the pencil",
      "The hard part isn't the technique. It's sitting on your hands.",
      "When a kid is stuck and you're tired, doing it yourself takes ninety seconds and doing it their way takes twenty minutes. Every parent has made that trade, and sometimes it's the right one — dinner is burning, you have to leave, fine.",
      "But the twenty-minute version is where the learning is. If you always take the pencil, the lesson they get isn't \"puzzles are doable.\" It's \"when things get hard, someone else finishes them.\" That one is expensive later.",
      "## Say the word out loud",
      "One small addition that costs nothing: name it while it's happening. \"That was a big problem, so you made it into small ones.\"",
      "Kids can do a thing long before they can describe it, and the describing is what makes it portable. A kid who can say what they did to the puzzle has a chance of doing it to a school project in four years. A kid who just got a tidy room has a tidy room.",
      "That's the whole idea behind Princess Penny's Problem-Solving Party — a big problem shows up, everybody panics for a page, and then Penny does the unglamorous thing and cuts it into pieces small enough to carry. It's a story rather than a lesson, which is the only way this goes down at bedtime. Read it a few times and the phrase starts coming out of them instead of you.",
    ],
    productSlug: "princess-pennys-problem-solving-party",
  },
];

export const postBySlug = (slug: string) => POSTS.find((p) => p.slug === slug);

export const sortedPosts = () =>
  [...POSTS].sort((a, b) => (a.date < b.date ? 1 : -1));
